name=puara-gestures
version=0.1.0
author=Eduardo Menses
maintainer=Eduardo Menses
sentence=a library implementing gestures for embedded systems.
paragraph=The puara-gestures library provides a set of tools for creating and managing high-level gestural descriptors using data from various sensors such as accelerometers, gyroscopes, and magnetometers. The library includes classes for handling different types of gestures, including shakes, rolls, tilts, jabs, and touches.
category=Sensors
url=https://github.com/Puara/puara-gestures
architectures=esp32
includes=puara_gestures.h
